POST http://0.0.0.0:3001/tanklevels/create
Content-Type: application/json

{
  "level": 100,
  "rssi": -50,
  "rsn": 27,
  "frequencyError": 2,
  "caughtAt": "2024-07-04, 14:25:31",
  "tank": {
    "arduinoId": 2,
    "gateway": {
      "arduinoId": 1
    }
  }
}